# Generated by Django 4.1.1 on 2022-09-24 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ('nombre',), 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('referencia', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('producto', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Producto')),
                ('marca', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio del Producto')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ('proveedor',),
            },
        ),
    ]
