# Generated by Django 4.1.1 on 2022-09-24 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0002_registrocompra_alter_proveedor_options_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrocompra',
            options={'ordering': ('registro',), 'verbose_name': 'Registro de Compra', 'verbose_name_plural': 'Registros de Compras'},
        ),
        migrations.AddField(
            model_name='registrocompra',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrocompra',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='registrocompra',
            name='hora',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registrocompra',
            name='producto',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nombre del Producto'),
        ),
        migrations.AddField(
            model_name='registrocompra',
            name='referencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='compras.pedido'),
        ),
        migrations.AddField(
            model_name='registrocompra',
            name='registro',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='registrocompra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='registrocompra',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='referencia',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
