# Generated by Django 4.1.1 on 2022-09-26 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_pedido_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocompra',
            name='referencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.pedido'),
        ),
    ]
