# Generated by Django 4.1.1 on 2022-09-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_registrocompra_referencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrocompra',
            options={'ordering': ('referencia',), 'verbose_name': 'Registro de Compra', 'verbose_name_plural': 'Registros de Compras'},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='registrocompra',
            name='registro',
        ),
        migrations.AddField(
            model_name='pedido',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='registrocompra',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='registrocompra',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio del Producto'),
        ),
        migrations.AddField(
            model_name='registrocompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
