# Generated by Django 4.1.1 on 2022-10-02 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_alter_registrocompra_options_remove_pedido_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
        migrations.CreateModel(
            name='PedidosDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Producto')),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio del Producto')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tasa_iva', models.FloatField(blank=True, default=0, null=True)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('pedidoref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.pedido')),
            ],
        ),
    ]
