# Generated by Django 4.1.1 on 2022-10-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_pedido_cantidad_pedido_precio_pedido_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(default=3),
        ),
    ]
