# Generated by Django 4.1.1 on 2022-10-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_alter_pedido_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='iva',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio',
            field=models.FloatField(default=0.0, verbose_name='Precio del Producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
