# Generated by Django 4.1.1 on 2022-10-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_alter_pedido_cantidad_alter_pedido_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='precio',
            field=models.IntegerField(default=0.0, verbose_name='Precio del Producto'),
        ),
        migrations.AlterField(
            model_name='registrocompra',
            name='producto',
            field=models.IntegerField(max_length=100, null=True, unique=True, verbose_name='Nombre del Producto'),
        ),
    ]
