# Generated by Django 4.1.1 on 2022-10-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_alter_pedido_precio_alter_registrocompra_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='precio',
            field=models.FloatField(default=0.0, verbose_name='Precio del Producto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registrocompra',
            name='producto',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nombre del Producto'),
        ),
    ]
