# Generated by Django 4.1.1 on 2022-10-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_alter_pedido_precio_alter_proveedor_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='iva',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio',
            field=models.FloatField(verbose_name='Precio del Producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='registrocompra',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrocompra',
            name='iva',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='registrocompra',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio del Producto'),
        ),
        migrations.AlterField(
            model_name='registrocompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='registrocompra',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
